### ISSUE TITLE
light mode

### ISSUE THREAD

**Issue by mizchi** [mizchi/mdbuf#14]
```css
textarea {
    font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,Courier,monospace;
    background: #fff;
    color: black;
}
```
